In [43]:
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd

In [44]:
df=pd.read_csv('Weather.csv')
df

Weather Play
0      Rainy  Yes
1      Sunny  Yes
2   Overcast  Yes
3   Overcast  Yes
4      Sunny   No
5      Rainy  Yes
6      Sunny  Yes
7   Overcast  Yes
8      Rainy   No
9      Sunny   No
10     Sunny  Yes
11     Rainy   No
12  Overcast  Yes
13  Overcast  Yes

In [45]:
df['Weather'].value_counts()

Weather
Sunny       5
Overcast    5
Rainy       4
Name: count, dtype: int64

In [46]:
df['Play'].value_counts()

Play
Yes    10
No      4
Name: count, dtype: int64

In [47]:
encoded={
        "Weather":{"Sunny":1,"Rainy":2,"Overcast":3},
        "Play":{"Yes":1,"No":2}
        }

In [48]:
encoded

{'Weather': {'Sunny': 1, 'Rainy': 2, 'Overcast': 3},
 'Play': {'Yes': 1, 'No': 2}}

In [49]:
df=df.replace(encoded)
df

Weather  Play
0         2     1
1         1     1
2         3     1
3         3     1
4         1     2
5         2     1
6         1     1
7         3     1
8         2     2
9         1     2
10        1     1
11        2     2
12        3     1
13        3     1

In [50]:
x=df.iloc[:,0]
y=df.iloc[:,1]

In [54]:
x=np.array(x).reshape(-1,1)
x

array([[2],
       [1],
       [3],
       [3],
       [1],
       [2],
       [1],
       [3],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3]], dtype=int64)

In [55]:
y=np.array(y).reshape(-1,1)
y

array([[1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1]], dtype=int64)

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [76]:
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

c:\Users\biswa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [77]:
y_pred = classifier.predict(x_test)  

In [78]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  
cm

array([[0, 1],
       [2, 1]], dtype=int64)

In [79]:
classifier.score(y_test,y_pred)

0.75